import { Account, MediaAsset, Campaign, QueueJob, SystemUser, CopyItem, HashtagSet, CtaItem } from '@/types';

/**
 * 20 Contas Iniciais Zeradas e Prontas para Operação Real (10 HOT + 10 DROPSHIPPING)
 */
export const INITIAL_ACCOUNTS: Account[] = [
  // --- 5 CONTAS HOT PORTUGAL ---
  {
    id: 'acc_hot_pt_01',
    name: 'HOT Portugal 01',
    username: '@hot_vip_pt01',
    passwordHash: 'vault_encrypted',
    category: 'HOT',
    country: 'Portugal',
    countryCode: 'PT',
    language: 'Português (Portugal)',
    languageCode: 'PT-PT',
    timezone: 'Europe/Lisbon',
    city: 'Lisboa',
    state: 'LIS',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_hot_pt_01',
      ip: '185.220.101.5',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 0,
      status: 'TESTING',
    },
    cookies: '',
    status: 'OFFLINE',
    lastLogin: 'Nunca',
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Conta HOT Portugal 01 — Adicione o proxy real e configure os cookies de sessão.',
    tags: ['HOT', 'PT', 'Lisboa'],
  },
  {
    id: 'acc_hot_pt_02',
    name: 'HOT Portugal 02',
    username: '@hot_vip_pt02',
    passwordHash: 'vault_encrypted',
    category: 'HOT',
    country: 'Portugal',
    countryCode: 'PT',
    language: 'Português (Portugal)',
    languageCode: 'PT-PT',
    timezone: 'Europe/Lisbon',
    city: 'Porto',
    state: 'POR',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_hot_pt_02',
      ip: '185.220.101.6',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 0,
      status: 'TESTING',
    },
    cookies: '',
    status: 'OFFLINE',
    lastLogin: 'Nunca',
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Conta HOT Portugal 02 — Porto.',
    tags: ['HOT', 'PT', 'Porto'],
  },
  {
    id: 'acc_hot_pt_03',
    name: 'HOT Portugal 03',
    username: '@hot_vip_pt03',
    passwordHash: 'vault_encrypted',
    category: 'HOT',
    country: 'Portugal',
    countryCode: 'PT',
    language: 'Português (Portugal)',
    languageCode: 'PT-PT',
    timezone: 'Europe/Lisbon',
    city: 'Braga',
    state: 'BRG',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_hot_pt_03',
      ip: '185.220.101.7',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 0,
      status: 'TESTING',
    },
    cookies: '',
    status: 'OFFLINE',
    lastLogin: 'Nunca',
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Conta HOT Portugal 03 — Braga.',
    tags: ['HOT', 'PT', 'Braga'],
  },
  {
    id: 'acc_hot_pt_04',
    name: 'HOT Portugal 04',
    username: '@hot_vip_pt04',
    passwordHash: 'vault_encrypted',
    category: 'HOT',
    country: 'Portugal',
    countryCode: 'PT',
    language: 'Português (Portugal)',
    languageCode: 'PT-PT',
    timezone: 'Europe/Lisbon',
    city: 'Coimbra',
    state: 'COI',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_hot_pt_04',
      ip: '185.220.101.8',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 0,
      status: 'TESTING',
    },
    cookies: '',
    status: 'OFFLINE',
    lastLogin: 'Nunca',
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Conta HOT Portugal 04 — Coimbra.',
    tags: ['HOT', 'PT', 'Coimbra'],
  },
  {
    id: 'acc_hot_pt_05',
    name: 'HOT Portugal 05',
    username: '@hot_vip_pt05',
    passwordHash: 'vault_encrypted',
    category: 'HOT',
    country: 'Portugal',
    countryCode: 'PT',
    language: 'Português (Portugal)',
    languageCode: 'PT-PT',
    timezone: 'Europe/Lisbon',
    city: 'Faro',
    state: 'FAR',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_hot_pt_05',
      ip: '185.220.101.9',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 0,
      status: 'TESTING',
    },
    cookies: '',
    status: 'OFFLINE',
    lastLogin: 'Nunca',
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Conta HOT Portugal 05 — Faro / Algarve.',
    tags: ['HOT', 'PT', 'Faro'],
  },

  // --- 5 CONTAS HOT ESPANHA ---
  {
    id: 'acc_hot_es_01',
    name: 'HOT España 01',
    username: '@hot_vip_es01',
    passwordHash: 'vault_encrypted',
    category: 'HOT',
    country: 'Espanha',
    countryCode: 'ES',
    language: 'Espanhol',
    languageCode: 'ES',
    timezone: 'Europe/Madrid',
    city: 'Madrid',
    state: 'MAD',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_hot_es_01',
      ip: '185.220.101.10',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 0,
      status: 'TESTING',
    },
    cookies: '',
    status: 'OFFLINE',
    lastLogin: 'Nunca',
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Conta HOT Espanha 01 — Madrid.',
    tags: ['HOT', 'ES', 'Madrid'],
  },
  {
    id: 'acc_hot_es_02',
    name: 'HOT España 02',
    username: '@hot_vip_es02',
    passwordHash: 'vault_encrypted',
    category: 'HOT',
    country: 'Espanha',
    countryCode: 'ES',
    language: 'Espanhol',
    languageCode: 'ES',
    timezone: 'Europe/Madrid',
    city: 'Barcelona',
    state: 'CAT',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_hot_es_02',
      ip: '185.220.101.11',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 0,
      status: 'TESTING',
    },
    cookies: '',
    status: 'OFFLINE',
    lastLogin: 'Nunca',
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Conta HOT Espanha 02 — Barcelona.',
    tags: ['HOT', 'ES', 'Barcelona'],
  },
  {
    id: 'acc_hot_es_03',
    name: 'HOT España 03',
    username: '@hot_vip_es03',
    passwordHash: 'vault_encrypted',
    category: 'HOT',
    country: 'Espanha',
    countryCode: 'ES',
    language: 'Espanhol',
    languageCode: 'ES',
    timezone: 'Europe/Madrid',
    city: 'Sevilla',
    state: 'AND',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_hot_es_03',
      ip: '185.220.101.12',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 0,
      status: 'TESTING',
    },
    cookies: '',
    status: 'OFFLINE',
    lastLogin: 'Nunca',
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Conta HOT Espanha 03 — Sevilla.',
    tags: ['HOT', 'ES', 'Sevilla'],
  },
  {
    id: 'acc_hot_es_04',
    name: 'HOT España 04',
    username: '@hot_vip_es04',
    passwordHash: 'vault_encrypted',
    category: 'HOT',
    country: 'Espanha',
    countryCode: 'ES',
    language: 'Espanhol',
    languageCode: 'ES',
    timezone: 'Europe/Madrid',
    city: 'Valencia',
    state: 'VAL',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_hot_es_04',
      ip: '185.220.101.13',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 0,
      status: 'TESTING',
    },
    cookies: '',
    status: 'OFFLINE',
    lastLogin: 'Nunca',
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Conta HOT Espanha 04 — Valencia.',
    tags: ['HOT', 'ES', 'Valencia'],
  },
  {
    id: 'acc_hot_es_05',
    name: 'HOT España 05',
    username: '@hot_vip_es05',
    passwordHash: 'vault_encrypted',
    category: 'HOT',
    country: 'Espanha',
    countryCode: 'ES',
    language: 'Espanhol',
    languageCode: 'ES',
    timezone: 'Europe/Madrid',
    city: 'Bilbao',
    state: 'PVA',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_hot_es_05',
      ip: '185.220.101.14',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 0,
      status: 'TESTING',
    },
    cookies: '',
    status: 'OFFLINE',
    lastLogin: 'Nunca',
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Conta HOT Espanha 05 — Bilbao / País Basco.',
    tags: ['HOT', 'ES', 'Bilbao'],
  },

  // --- 10 CONTAS DROPSHIPPING ---
  {
    id: 'acc_drop_01',
    name: 'DROP Store 01 (US)',
    username: '@trendstore_us',
    passwordHash: 'vault_encrypted',
    category: 'DROP',
    country: 'Estados Unidos',
    countryCode: 'US',
    language: 'Inglês',
    languageCode: 'EN-US',
    timezone: 'America/New_York',
    city: 'New York',
    state: 'NY',
    currency: 'USD ($)',
    dateFormat: 'MM/DD/YYYY',
    timeFormat: '12h (AM/PM)',
    proxy: {
      id: 'px_drop_01',
      ip: '198.51.100.10',
      port: 8080,
      protocol: 'HTTPS',
      latencyMs: 115,
      status: 'ACTIVE',
    },
    cookies: '',
    status: 'ONLINE',
    lastLogin: new Date().toISOString(),
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Loja Dropshipping US — Produtos Gadgets',
    tags: ['DROP', 'USA', 'STORE'],
  },
  {
    id: 'acc_drop_02',
    name: 'DROP Store 02 (UK)',
    username: '@trendstore_uk',
    passwordHash: 'vault_encrypted',
    category: 'DROP',
    country: 'Reino Unido',
    countryCode: 'UK',
    language: 'Inglês',
    languageCode: 'EN-UK',
    timezone: 'Europe/London',
    city: 'London',
    state: 'ENG',
    currency: 'GBP (£)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_drop_02',
      ip: '198.51.100.11',
      port: 8080,
      protocol: 'HTTPS',
      latencyMs: 135,
      status: 'ACTIVE',
    },
    cookies: '',
    status: 'ONLINE',
    lastLogin: new Date().toISOString(),
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Loja Dropshipping UK — Utilidades',
    tags: ['DROP', 'UK', 'STORE'],
  },
  {
    id: 'acc_drop_03',
    name: 'DROP Store 03 (BR)',
    username: '@trendstore_br',
    passwordHash: 'vault_encrypted',
    category: 'DROP',
    country: 'Brasil',
    countryCode: 'BR',
    language: 'Português',
    languageCode: 'PT-BR',
    timezone: 'America/Sao_Paulo',
    city: 'São Paulo',
    state: 'SP',
    currency: 'BRL (R$)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_drop_03',
      ip: '177.185.200.15',
      port: 1080,
      protocol: 'HTTP',
      latencyMs: 38,
      status: 'ACTIVE',
    },
    cookies: '',
    status: 'ONLINE',
    lastLogin: new Date().toISOString(),
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Loja Dropshipping Brasil — Shopify VIP',
    tags: ['DROP', 'BR', 'SHOPIFY'],
  },
  {
    id: 'acc_drop_04',
    name: 'DROP Store 04 (ES)',
    username: '@trendstore_es',
    passwordHash: 'vault_encrypted',
    category: 'DROP',
    country: 'Espanha',
    countryCode: 'ES',
    language: 'Espanhol',
    languageCode: 'ES',
    timezone: 'Europe/Madrid',
    city: 'Madrid',
    state: 'MD',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_drop_04',
      ip: '198.51.100.12',
      port: 8080,
      protocol: 'HTTPS',
      latencyMs: 152,
      status: 'ACTIVE',
    },
    cookies: '',
    status: 'ONLINE',
    lastLogin: new Date().toISOString(),
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Loja Dropshipping Espanha',
    tags: ['DROP', 'ES'],
  },
  {
    id: 'acc_drop_05',
    name: 'DROP Store 05 (FR)',
    username: '@trendstore_fr',
    passwordHash: 'vault_encrypted',
    category: 'DROP',
    country: 'França',
    countryCode: 'FR',
    language: 'Francês',
    languageCode: 'FR',
    timezone: 'Europe/Paris',
    city: 'Paris',
    state: 'IDF',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_drop_05',
      ip: '198.51.100.13',
      port: 8080,
      protocol: 'HTTPS',
      latencyMs: 158,
      status: 'ACTIVE',
    },
    cookies: '',
    status: 'ONLINE',
    lastLogin: new Date().toISOString(),
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Loja Dropshipping França',
    tags: ['DROP', 'FR'],
  },
  {
    id: 'acc_drop_06',
    name: 'DROP Store 06 (DE)',
    username: '@trendstore_de',
    passwordHash: 'vault_encrypted',
    category: 'DROP',
    country: 'Alemanha',
    countryCode: 'DE',
    language: 'Alemão',
    languageCode: 'DE',
    timezone: 'Europe/Berlin',
    city: 'Berlin',
    state: 'BE',
    currency: 'EUR (€)',
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_drop_06',
      ip: '198.51.100.14',
      port: 8080,
      protocol: 'HTTPS',
      latencyMs: 148,
      status: 'ACTIVE',
    },
    cookies: '',
    status: 'ONLINE',
    lastLogin: new Date().toISOString(),
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Loja Dropshipping Alemanha',
    tags: ['DROP', 'DE'],
  },
  {
    id: 'acc_drop_07',
    name: 'DROP Store 07 (IT)',
    username: '@trendstore_it',
    passwordHash: 'vault_encrypted',
    category: 'DROP',
    country: 'Itália',
    countryCode: 'IT',
    language: 'Italiano',
    languageCode: 'IT',
    timezone: 'Europe/Rome',
    city: 'Roma',
    state: 'RM',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'px_drop_07',
      ip: '198.51.100.15',
      port: 8080,
      protocol: 'HTTPS',
      latencyMs: 154,
      status: 'ACTIVE',
    },
    cookies: '',
    status: 'ONLINE',
    lastLogin: new Date().toISOString(),
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Loja Dropshipping Itália',
    tags: ['DROP', 'IT'],
  },
  {
    id: 'acc_drop_08',
    name: 'DROP Store 08 (CA)',
    username: '@trendstore_ca',
    passwordHash: 'vault_encrypted',
    category: 'DROP',
    country: 'Canadá',
    countryCode: 'CA',
    language: 'Inglês',
    languageCode: 'EN-CA',
    timezone: 'America/Toronto',
    city: 'Toronto',
    state: 'ON',
    currency: 'CAD ($)',
    dateFormat: 'YYYY-MM-DD',
    timeFormat: '12h (AM/PM)',
    proxy: {
      id: 'px_drop_08',
      ip: '198.51.100.16',
      port: 8080,
      protocol: 'HTTPS',
      latencyMs: 132,
      status: 'ACTIVE',
    },
    cookies: '',
    status: 'ONLINE',
    lastLogin: new Date().toISOString(),
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Loja Dropshipping Canadá',
    tags: ['DROP', 'CA'],
  },
  {
    id: 'acc_drop_09',
    name: 'DROP Store 09 (AU)',
    username: '@trendstore_au',
    passwordHash: 'vault_encrypted',
    category: 'DROP',
    country: 'Austrália',
    countryCode: 'AU',
    language: 'Inglês',
    languageCode: 'EN-AU',
    timezone: 'Australia/Sydney',
    city: 'Sydney',
    state: 'NSW',
    currency: 'AUD ($)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h (AM/PM)',
    proxy: {
      id: 'px_drop_09',
      ip: '198.51.100.17',
      port: 8080,
      protocol: 'HTTPS',
      latencyMs: 215,
      status: 'ACTIVE',
    },
    cookies: '',
    status: 'ONLINE',
    lastLogin: new Date().toISOString(),
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Loja Dropshipping Austrália',
    tags: ['DROP', 'AU'],
  },
  {
    id: 'acc_drop_10',
    name: 'DROP Store 10 (MX)',
    username: '@trendstore_mx',
    passwordHash: 'vault_encrypted',
    category: 'DROP',
    country: 'México',
    countryCode: 'MX',
    language: 'Espanhol',
    languageCode: 'ES-MX',
    timezone: 'America/Mexico_City',
    city: 'Ciudad de Mexico',
    state: 'CDMX',
    currency: 'MXN ($)',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h (AM/PM)',
    proxy: {
      id: 'px_drop_10',
      ip: '198.51.100.18',
      port: 8080,
      protocol: 'HTTPS',
      latencyMs: 112,
      status: 'ACTIVE',
    },
    cookies: '',
    status: 'ONLINE',
    lastLogin: new Date().toISOString(),
    lastPublication: 'Sem publicações',
    publishedCount: 0,
    errorCount: 0,
    notes: 'Loja Dropshipping México',
    tags: ['DROP', 'MX'],
  },
];

/**
 * Biblioteca Central de Mídias Limpa e Zerada
 * (Pronta para você fazer upload das suas 150 mídias 9:16 reais)
 */
export const INITIAL_MEDIA_ASSETS: MediaAsset[] = [];
export const INITIAL_MEDIA: MediaAsset[] = [];
export const INITIAL_QUEUE_JOBS: QueueJob[] = [];
export const INITIAL_CAMPAIGNS: Campaign[] = [];
export const INITIAL_EXECUTION_LOGS = [];

export const INITIAL_USERS: SystemUser[] = [
  {
    id: 'usr_admin',
    name: 'Operador VIP (Admin)',
    email: 'admin@omnimedia.saas',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    twoFactorEnabled: true,
    lastActive: new Date().toISOString(),
  },
];

export const INITIAL_COPYS: CopyItem[] = [];
export const INITIAL_HASHTAGS: HashtagSet[] = [];
export const INITIAL_CTAS: CtaItem[] = [];
