import {
  Account,
  MediaAsset,
  CopyItem,
  HashtagSet,
  CtaItem,
  MusicTrack,
  Campaign,
  QueueJob,
  ExecutionLog,
  SystemUser,
} from '@/types';

export const INITIAL_USERS: SystemUser[] = [
  {
    id: 'usr_admin',
    name: 'Júlia Administrator',
    email: 'admin@omnimedia.saas',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    twoFactorEnabled: true,
    lastActive: 'Just now',
  },
  {
    id: 'usr_op1',
    name: 'Carlos Santos (HOT Mgr)',
    email: 'carlos@omnimedia.saas',
    role: 'MANAGER',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    twoFactorEnabled: false,
    lastActive: '12 mins ago',
  },
  {
    id: 'usr_op2',
    name: 'Mariana Silva (DROP Mgr)',
    email: 'mariana@omnimedia.saas',
    role: 'MANAGER',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    twoFactorEnabled: true,
    lastActive: '1 hour ago',
  },
  {
    id: 'usr_op3',
    name: 'Lucas Ferreira (Media Editor)',
    email: 'lucas@omnimedia.saas',
    role: 'EDITOR',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    twoFactorEnabled: false,
    lastActive: '3 hours ago',
  },
  {
    id: 'usr_op4',
    name: 'Sophia Chen (Global Specialist)',
    email: 'sophia@omnimedia.saas',
    role: 'EDITOR',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    twoFactorEnabled: true,
    lastActive: '5 hours ago',
  },
  {
    id: 'usr_op5',
    name: 'Rafael Oliveira (Automation Tech)',
    email: 'rafael@omnimedia.saas',
    role: 'EDITOR',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    twoFactorEnabled: false,
    lastActive: 'Yesterday',
  },
];

export const INITIAL_ACCOUNTS: Account[] = [
  // 10 HOT Accounts
  {
    id: 'acc_hot_01',
    name: 'Bella VIP Model BR',
    username: '@bella_vip_br',
    passwordHash: '••••••••••••',
    category: 'HOT',
    country: 'Brasil',
    countryCode: 'BR',
    language: 'Português Brasil',
    languageCode: 'PT-BR',
    timezone: 'America/Sao_Paulo',
    city: 'São Paulo',
    state: 'SP',
    currency: 'BRL',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_01',
      ip: '177.12.89.45',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 42,
      status: 'ACTIVE',
      lastTestedAt: '10 mins ago',
    },
    cookies: 'sessionid=9832145789; ds_user_id=8923412',
    status: 'ONLINE',
    lastLogin: '2026-08-03 11:45',
    lastPublication: '2026-08-03 09:00',
    publishedCount: 142,
    errorCount: 1,
    notes: 'Primary HOT revenue driver in Brazil market.',
    tags: ['HOT', 'VIP', 'Reels', 'PT-BR'],
  },
  {
    id: 'acc_hot_02',
    name: 'Camila Luxe PT',
    username: '@camila_luxe_pt',
    passwordHash: '••••••••••••',
    category: 'HOT',
    country: 'Portugal',
    countryCode: 'PT',
    language: 'Português Portugal',
    languageCode: 'PT-PT',
    timezone: 'Europe/Lisbon',
    city: 'Lisboa',
    state: 'Lisboa',
    currency: 'EUR',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_02',
      ip: '185.220.101.5',
      port: 1080,
      protocol: 'HTTPS',
      latencyMs: 88,
      status: 'ACTIVE',
      lastTestedAt: '12 mins ago',
    },
    cookies: 'sessionid=7721839210; ds_user_id=3321456',
    status: 'ONLINE',
    lastLogin: '2026-08-03 11:30',
    lastPublication: '2026-08-03 09:00',
    publishedCount: 98,
    errorCount: 0,
    notes: 'Lisbon targeted account.',
    tags: ['HOT', 'Portugal', 'Lisbon'],
  },
  {
    id: 'acc_hot_03',
    name: 'Scarlett Glam US',
    username: '@scarlett_glam_us',
    passwordHash: '••••••••••••',
    category: 'HOT',
    country: 'United States',
    countryCode: 'US',
    language: 'English US',
    languageCode: 'EN-US',
    timezone: 'America/New_York',
    city: 'New York',
    state: 'NY',
    currency: 'USD',
    dateFormat: 'MM/DD/YYYY',
    timeFormat: '12h',
    proxy: {
      id: 'prx_03',
      ip: '104.28.19.120',
      port: 3128,
      protocol: 'HTTP',
      latencyMs: 35,
      status: 'ACTIVE',
      lastTestedAt: '5 mins ago',
    },
    cookies: 'sessionid=1129384756; ds_user_id=9928174',
    status: 'ONLINE',
    lastLogin: '2026-08-03 10:15',
    lastPublication: '2026-08-03 09:00',
    publishedCount: 230,
    errorCount: 2,
    notes: 'US East Coast high volume account.',
    tags: ['HOT', 'US', 'Tier1', 'TikTok'],
  },
  {
    id: 'acc_hot_04',
    name: 'Chloe Noir FR',
    username: '@chloe_noir_fr',
    passwordHash: '••••••••••••',
    category: 'HOT',
    country: 'France',
    countryCode: 'FR',
    language: 'Français',
    languageCode: 'FR',
    timezone: 'Europe/Paris',
    city: 'Paris',
    state: 'Île-de-France',
    currency: 'EUR',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_04',
      ip: '195.154.122.90',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 95,
      status: 'ACTIVE',
      lastTestedAt: '18 mins ago',
    },
    cookies: 'sessionid=4481273921; ds_user_id=1120495',
    status: 'ONLINE',
    lastLogin: '2026-08-03 08:30',
    lastPublication: '2026-08-02 21:00',
    publishedCount: 84,
    errorCount: 0,
    notes: 'Paris high luxury HOT tier.',
    tags: ['HOT', 'France', 'Paris'],
  },
  {
    id: 'acc_hot_05',
    name: 'Elena Rose DE',
    username: '@elena_rose_de',
    passwordHash: '••••••••••••',
    category: 'HOT',
    country: 'Germany',
    countryCode: 'DE',
    language: 'Deutsch',
    languageCode: 'DE',
    timezone: 'Europe/Berlin',
    city: 'Berlin',
    state: 'Berlin',
    currency: 'EUR',
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_05',
      ip: '188.40.142.11',
      port: 1080,
      protocol: 'SOCKS5',
      latencyMs: 110,
      status: 'ACTIVE',
      lastTestedAt: '25 mins ago',
    },
    cookies: 'sessionid=9928374102; ds_user_id=4492103',
    status: 'ONLINE',
    lastLogin: '2026-08-03 09:20',
    lastPublication: '2026-08-03 09:00',
    publishedCount: 112,
    errorCount: 1,
    notes: 'German market converter.',
    tags: ['HOT', 'DE', 'Berlin'],
  },
  {
    id: 'acc_hot_06',
    name: 'Sophia Bella IT',
    username: '@sophia_bella_it',
    passwordHash: '••••••••••••',
    category: 'HOT',
    country: 'Italy',
    countryCode: 'IT',
    language: 'Italiano',
    languageCode: 'IT',
    timezone: 'Europe/Rome',
    city: 'Milano',
    state: 'Lombardia',
    currency: 'EUR',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_06',
      ip: '93.184.220.29',
      port: 8080,
      protocol: 'HTTPS',
      latencyMs: 105,
      status: 'ACTIVE',
      lastTestedAt: '30 mins ago',
    },
    cookies: 'sessionid=6618293019; ds_user_id=7739102',
    status: 'ONLINE',
    lastLogin: '2026-08-03 07:45',
    lastPublication: '2026-08-03 09:00',
    publishedCount: 76,
    errorCount: 0,
    notes: 'Milan fashion HOT account.',
    tags: ['HOT', 'IT', 'Milano'],
  },
  {
    id: 'acc_hot_07',
    name: 'Lucia Sun ES',
    username: '@lucia_sun_es',
    passwordHash: '••••••••••••',
    category: 'HOT',
    country: 'Spain',
    countryCode: 'ES',
    language: 'Español',
    languageCode: 'ES',
    timezone: 'Europe/Madrid',
    city: 'Madrid',
    state: 'Madrid',
    currency: 'EUR',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_07',
      ip: '185.15.58.12',
      port: 3128,
      protocol: 'HTTP',
      latencyMs: 78,
      status: 'ACTIVE',
      lastTestedAt: '14 mins ago',
    },
    cookies: 'sessionid=3391029384; ds_user_id=2281940',
    status: 'ONLINE',
    lastLogin: '2026-08-03 11:10',
    lastPublication: '2026-08-03 09:00',
    publishedCount: 165,
    errorCount: 1,
    notes: 'Spain & LATAM reach account.',
    tags: ['HOT', 'ES', 'Madrid'],
  },
  {
    id: 'acc_hot_08',
    name: 'Vanessa Maple CA',
    username: '@vanessa_maple_ca',
    passwordHash: '••••••••••••',
    category: 'HOT',
    country: 'Canada',
    countryCode: 'CA',
    language: 'English US',
    languageCode: 'EN-US',
    timezone: 'America/Toronto',
    city: 'Toronto',
    state: 'ON',
    currency: 'CAD',
    dateFormat: 'YYYY-MM-DD',
    timeFormat: '12h',
    proxy: {
      id: 'prx_08',
      ip: '198.51.100.42',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 62,
      status: 'ACTIVE',
      lastTestedAt: '8 mins ago',
    },
    cookies: 'sessionid=8830192837; ds_user_id=6649102',
    status: 'ONLINE',
    lastLogin: '2026-08-03 10:40',
    lastPublication: '2026-08-03 09:00',
    publishedCount: 120,
    errorCount: 0,
    notes: 'Canadian audience driver.',
    tags: ['HOT', 'CA', 'Toronto'],
  },
  {
    id: 'acc_hot_09',
    name: 'Maya UK Luxury',
    username: '@maya_uk_luxury',
    passwordHash: '••••••••••••',
    category: 'HOT',
    country: 'United Kingdom',
    countryCode: 'UK',
    language: 'English UK',
    languageCode: 'EN-UK',
    timezone: 'Europe/London',
    city: 'London',
    state: 'Greater London',
    currency: 'GBP',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_09',
      ip: '51.15.22.88',
      port: 1080,
      protocol: 'HTTPS',
      latencyMs: 70,
      status: 'ACTIVE',
      lastTestedAt: '4 mins ago',
    },
    cookies: 'sessionid=1192830491; ds_user_id=8830192',
    status: 'ONLINE',
    lastLogin: '2026-08-03 11:50',
    lastPublication: '2026-08-03 09:00',
    publishedCount: 189,
    errorCount: 0,
    notes: 'London high converter.',
    tags: ['HOT', 'UK', 'London'],
  },
  {
    id: 'acc_hot_10',
    name: 'Sanne Dutch NL',
    username: '@sanne_dutch_nl',
    passwordHash: '••••••••••••',
    category: 'HOT',
    country: 'Netherlands',
    countryCode: 'NL',
    language: 'Nederlands',
    languageCode: 'NL',
    timezone: 'Europe/Amsterdam',
    city: 'Amsterdam',
    state: 'North Holland',
    currency: 'EUR',
    dateFormat: 'DD-MM-YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_10',
      ip: '136.244.100.12',
      port: 3128,
      protocol: 'SOCKS5',
      latencyMs: 85,
      status: 'ACTIVE',
      lastTestedAt: '15 mins ago',
    },
    cookies: 'sessionid=5591029384; ds_user_id=3310492',
    status: 'ONLINE',
    lastLogin: '2026-08-03 09:10',
    lastPublication: '2026-08-03 09:00',
    publishedCount: 92,
    errorCount: 0,
    notes: 'Amsterdam targeted HOT account.',
    tags: ['HOT', 'NL', 'Amsterdam'],
  },

  // 10 DROPSHIPPING Accounts
  {
    id: 'acc_drop_01',
    name: 'TechGizmo Brasil',
    username: '@techgizmo_br',
    passwordHash: '••••••••••••',
    category: 'DROP',
    country: 'Brasil',
    countryCode: 'BR',
    language: 'Português Brasil',
    languageCode: 'PT-BR',
    timezone: 'America/Sao_Paulo',
    city: 'Curitiba',
    state: 'PR',
    currency: 'BRL',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_drop_01',
      ip: '191.252.180.12',
      port: 8080,
      protocol: 'HTTPS',
      latencyMs: 50,
      status: 'ACTIVE',
      lastTestedAt: '6 mins ago',
    },
    cookies: 'sessionid=7739102938; ds_user_id=1192837',
    status: 'ONLINE',
    lastLogin: '2026-08-03 11:55',
    lastPublication: '2026-08-03 11:00',
    publishedCount: 310,
    errorCount: 1,
    notes: 'Electronics & gadgets dropshipping store.',
    tags: ['DROP', 'Gadgets', 'Electronics', 'PT-BR'],
  },
  {
    id: 'acc_drop_02',
    name: 'Casa & Conforto PT',
    username: '@casa_conforto_pt',
    passwordHash: '••••••••••••',
    category: 'DROP',
    country: 'Portugal',
    countryCode: 'PT',
    language: 'Português Portugal',
    languageCode: 'PT-PT',
    timezone: 'Europe/Lisbon',
    city: 'Porto',
    state: 'Porto',
    currency: 'EUR',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_drop_02',
      ip: '185.190.140.22',
      port: 1080,
      protocol: 'SOCKS5',
      latencyMs: 92,
      status: 'ACTIVE',
      lastTestedAt: '20 mins ago',
    },
    cookies: 'sessionid=4491029381; ds_user_id=5591029',
    status: 'ONLINE',
    lastLogin: '2026-08-03 10:20',
    lastPublication: '2026-08-03 11:00',
    publishedCount: 145,
    errorCount: 0,
    notes: 'Home decor dropshipping store.',
    tags: ['DROP', 'Home', 'Portugal'],
  },
  {
    id: 'acc_drop_03',
    name: 'FlexFit Gear USA',
    username: '@flexfit_gear_usa',
    passwordHash: '••••••••••••',
    category: 'DROP',
    country: 'United States',
    countryCode: 'US',
    language: 'English US',
    languageCode: 'EN-US',
    timezone: 'America/Los_Angeles',
    city: 'Los Angeles',
    state: 'CA',
    currency: 'USD',
    dateFormat: 'MM/DD/YYYY',
    timeFormat: '12h',
    proxy: {
      id: 'prx_drop_03',
      ip: '64.227.10.155',
      port: 3128,
      protocol: 'HTTP',
      latencyMs: 48,
      status: 'ACTIVE',
      lastTestedAt: '3 mins ago',
    },
    cookies: 'sessionid=2201928374; ds_user_id=8839102',
    status: 'ONLINE',
    lastLogin: '2026-08-03 11:00',
    lastPublication: '2026-08-03 11:00',
    publishedCount: 420,
    errorCount: 3,
    notes: 'Fitness & wellness physical products.',
    tags: ['DROP', 'Fitness', 'US', 'TikTokAds'],
  },
  {
    id: 'acc_drop_04',
    name: 'Maison Luxe FR',
    username: '@maison_luxe_fr',
    passwordHash: '••••••••••••',
    category: 'DROP',
    country: 'France',
    countryCode: 'FR',
    language: 'Français',
    languageCode: 'FR',
    timezone: 'Europe/Paris',
    city: 'Lyon',
    state: 'Rhône',
    currency: 'EUR',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_drop_04',
      ip: '51.159.20.10',
      port: 8080,
      protocol: 'SOCKS5',
      latencyMs: 98,
      status: 'ACTIVE',
      lastTestedAt: '16 mins ago',
    },
    cookies: 'sessionid=8820192834; ds_user_id=3301928',
    status: 'ONLINE',
    lastLogin: '2026-08-03 08:50',
    lastPublication: '2026-08-03 11:00',
    publishedCount: 110,
    errorCount: 0,
    notes: 'French kitchen & dining gadgets.',
    tags: ['DROP', 'France', 'Kitchen'],
  },
  {
    id: 'acc_drop_05',
    name: 'Nordic Clean DE',
    username: '@nordic_clean_de',
    passwordHash: '••••••••••••',
    category: 'DROP',
    country: 'Germany',
    countryCode: 'DE',
    language: 'Deutsch',
    languageCode: 'DE',
    timezone: 'Europe/Berlin',
    city: 'Frankfurt',
    state: 'Hessen',
    currency: 'EUR',
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_drop_05',
      ip: '159.69.110.45',
      port: 1080,
      protocol: 'HTTPS',
      latencyMs: 115,
      status: 'ACTIVE',
      lastTestedAt: '22 mins ago',
    },
    cookies: 'sessionid=3301928374; ds_user_id=7710293',
    status: 'ONLINE',
    lastLogin: '2026-08-03 09:40',
    lastPublication: '2026-08-03 11:00',
    publishedCount: 175,
    errorCount: 1,
    notes: 'Cleaning & organization products.',
    tags: ['DROP', 'Germany', 'Cleaning'],
  },
  {
    id: 'acc_drop_06',
    name: 'Cucina Bella IT',
    username: '@cucina_bella_it',
    passwordHash: '••••••••••••',
    category: 'DROP',
    country: 'Italy',
    countryCode: 'IT',
    language: 'Italiano',
    languageCode: 'IT',
    timezone: 'Europe/Rome',
    city: 'Roma',
    state: 'Lazio',
    currency: 'EUR',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_drop_06',
      ip: '109.168.10.88',
      port: 8080,
      protocol: 'HTTP',
      latencyMs: 102,
      status: 'ACTIVE',
      lastTestedAt: '11 mins ago',
    },
    cookies: 'sessionid=9910293847; ds_user_id=4401928',
    status: 'ONLINE',
    lastLogin: '2026-08-03 07:20',
    lastPublication: '2026-08-03 11:00',
    publishedCount: 88,
    errorCount: 0,
    notes: 'Italian culinary gadgets.',
    tags: ['DROP', 'Italy', 'Kitchen'],
  },
  {
    id: 'acc_drop_07',
    name: 'Moda Rapida ES',
    username: '@moda_rapida_es',
    passwordHash: '••••••••••••',
    category: 'DROP',
    country: 'Spain',
    countryCode: 'ES',
    language: 'Español',
    languageCode: 'ES',
    timezone: 'Europe/Madrid',
    city: 'Barcelona',
    state: 'Catalunya',
    currency: 'EUR',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_drop_07',
      ip: '178.32.190.15',
      port: 3128,
      protocol: 'SOCKS5',
      latencyMs: 82,
      status: 'ACTIVE',
      lastTestedAt: '19 mins ago',
    },
    cookies: 'sessionid=2210928374; ds_user_id=9910293',
    status: 'ONLINE',
    lastLogin: '2026-08-03 10:50',
    lastPublication: '2026-08-03 11:00',
    publishedCount: 205,
    errorCount: 0,
    notes: 'Fashion accessories dropshipping.',
    tags: ['DROP', 'Spain', 'Fashion'],
  },
  {
    id: 'acc_drop_08',
    name: 'Aura Glow Canada',
    username: '@aura_glow_ca',
    passwordHash: '••••••••••••',
    category: 'DROP',
    country: 'Canada',
    countryCode: 'CA',
    language: 'English US',
    languageCode: 'EN-US',
    timezone: 'America/Vancouver',
    city: 'Vancouver',
    state: 'BC',
    currency: 'CAD',
    dateFormat: 'YYYY-MM-DD',
    timeFormat: '12h',
    proxy: {
      id: 'prx_drop_08',
      ip: '142.93.150.80',
      port: 8080,
      protocol: 'HTTPS',
      latencyMs: 68,
      status: 'ACTIVE',
      lastTestedAt: '13 mins ago',
    },
    cookies: 'sessionid=7710293845; ds_user_id=1102938',
    status: 'ONLINE',
    lastLogin: '2026-08-03 09:00',
    lastPublication: '2026-08-03 11:00',
    publishedCount: 130,
    errorCount: 0,
    notes: 'Skincare & LED beauty devices.',
    tags: ['DROP', 'Beauty', 'Canada'],
  },
  {
    id: 'acc_drop_09',
    name: 'Smart Living UK',
    username: '@smart_living_uk',
    passwordHash: '••••••••••••',
    category: 'DROP',
    country: 'United Kingdom',
    countryCode: 'UK',
    language: 'English UK',
    languageCode: 'EN-UK',
    timezone: 'Europe/London',
    city: 'Manchester',
    state: 'Greater Manchester',
    currency: 'GBP',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_drop_09',
      ip: '46.101.50.99',
      port: 1080,
      protocol: 'SOCKS5',
      latencyMs: 74,
      status: 'ACTIVE',
      lastTestedAt: '7 mins ago',
    },
    cookies: 'sessionid=8810293847; ds_user_id=2201928',
    status: 'ONLINE',
    lastLogin: '2026-08-03 11:40',
    lastPublication: '2026-08-03 11:00',
    publishedCount: 290,
    errorCount: 1,
    notes: 'Smart home gadgets.',
    tags: ['DROP', 'UK', 'SmartHome'],
  },
  {
    id: 'acc_drop_10',
    name: 'SlimFit Dutch NL',
    username: '@slimfit_nl',
    passwordHash: '••••••••••••',
    category: 'DROP',
    country: 'Netherlands',
    countryCode: 'NL',
    language: 'Nederlands',
    languageCode: 'NL',
    timezone: 'Europe/Amsterdam',
    city: 'Rotterdam',
    state: 'South Holland',
    currency: 'EUR',
    dateFormat: 'DD-MM-YYYY',
    timeFormat: '24h',
    proxy: {
      id: 'prx_drop_10',
      ip: '95.217.40.10',
      port: 3128,
      protocol: 'HTTPS',
      latencyMs: 89,
      status: 'ACTIVE',
      lastTestedAt: '28 mins ago',
    },
    cookies: 'sessionid=3301928475; ds_user_id=6610293',
    status: 'ONLINE',
    lastLogin: '2026-08-03 10:10',
    lastPublication: '2026-08-03 11:00',
    publishedCount: 105,
    errorCount: 0,
    notes: 'Fitness apparel & accessories.',
    tags: ['DROP', 'NL', 'Fitness'],
  },
];

export const INITIAL_MEDIA_ASSETS: MediaAsset[] = [
  {
    id: 'med_01',
    title: 'Hot Summer Glam Promo Video',
    type: 'VIDEO',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-fashion-model-posing-in-a-black-outfit-41564-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&auto=format&fit=crop&q=80',
    category: 'HOT',
    languageCode: 'PT-BR',
    countryCode: 'BR',
    tags: ['HOT', 'Promo', 'Reels', 'VIP'],
    status: 'READY',
    dimensions: '1080x1920',
    durationSeconds: 18,
    sizeMb: 12.4,
    createdAt: '2026-08-01',
    variantsCount: 6,
  },
  {
    id: 'med_02',
    title: 'Bella Photoshoot Teaser Image',
    type: 'IMAGE',
    url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80',
    category: 'HOT',
    languageCode: 'PT-BR',
    countryCode: 'BR',
    tags: ['HOT', 'Image', 'Photoshoot'],
    status: 'READY',
    dimensions: '1080x1350',
    sizeMb: 3.8,
    createdAt: '2026-08-01',
    variantsCount: 8,
  },
  {
    id: 'med_03',
    title: 'Smart Mini Projector Product Reel',
    type: 'VIDEO',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-hands-holding-a-smartphone-with-green-screen-41551-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&auto=format&fit=crop&q=80',
    category: 'DROP',
    languageCode: 'EN-US',
    countryCode: 'US',
    tags: ['DROP', 'Gadget', 'Projector', 'Viral'],
    status: 'READY',
    dimensions: '1080x1920',
    durationSeconds: 24,
    sizeMb: 18.2,
    createdAt: '2026-08-02',
    variantsCount: 5,
  },
  {
    id: 'med_04',
    title: 'Posture Corrector Before/After Photo',
    type: 'IMAGE',
    url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop&q=80',
    category: 'DROP',
    languageCode: 'PT-BR',
    countryCode: 'BR',
    tags: ['DROP', 'Health', 'Posture'],
    status: 'READY',
    dimensions: '1080x1080',
    sizeMb: 2.1,
    createdAt: '2026-08-02',
    variantsCount: 4,
  },
];

export const INITIAL_COPYS: CopyItem[] = [
  {
    id: 'copy_hot_01',
    title: 'Exclusive Access Hook PT-BR',
    text: '🔥 Conteúdo inédito liberado hoje! Quer ver a versão sem censura? Clique no link da bio e entre no canal VIP agora mesmo. Vagas limitadas! 💋✨',
    languageCode: 'PT-BR',
    category: 'HOT',
    tags: ['VIP', 'BioLink', 'Limited'],
    status: 'ACTIVE',
    usedCount: 48,
  },
  {
    id: 'copy_hot_02',
    title: 'Exclusive Access Hook EN-US',
    text: '🔥 Uncensored preview dropped today! Want the full private gallery? Tap the link in bio right now to join the VIP lounge. Don’t miss out! 💋✨',
    languageCode: 'EN-US',
    category: 'HOT',
    tags: ['VIP', 'EN-US', 'BioLink'],
    status: 'ACTIVE',
    usedCount: 72,
  },
  {
    id: 'copy_drop_01',
    title: 'Problem-Solver Gadget Hook PT-BR',
    text: '😱 Chega de perrengue na cozinha! Esse produto novo economiza até 80% do seu tempo. Frete Grátis para todo o Brasil hoje! 👇',
    languageCode: 'PT-BR',
    category: 'DROP',
    tags: ['Kitchen', 'Offer', 'FreteGratis'],
    status: 'ACTIVE',
    usedCount: 110,
  },
  {
    id: 'copy_drop_02',
    title: 'Problem-Solver Gadget Hook EN-US',
    text: '😱 Stop wasting time on chores! This viral gadget cuts prep time in half. Get 50% OFF + Free Shipping worldwide today only! 👇',
    languageCode: 'EN-US',
    category: 'DROP',
    tags: ['Viral', 'Discount', 'FreeShipping'],
    status: 'ACTIVE',
    usedCount: 185,
  },
];

export const INITIAL_HASHTAGS: HashtagSet[] = [
  {
    id: 'hash_hot_br',
    title: 'HOT Brasil Auto-Rotate Set',
    hashtags: ['#modelsbr', '#vipaccess', '#lifestyle', '#aesthetic', '#reelsbr', '#viralvideo', '#fashionmodel', '#exclusivelines'],
    languageCode: 'PT-BR',
    countryCode: 'BR',
    category: 'HOT',
    tags: ['PT-BR', 'HOT'],
    status: 'ACTIVE',
  },
  {
    id: 'hash_hot_us',
    title: 'HOT USA Viral Set',
    hashtags: ['#usmodels', '#vipglam', '#trendingreels', '#foryou', '#aestheticmode', '#modelsofinstagram', '#viralus'],
    languageCode: 'EN-US',
    countryCode: 'US',
    category: 'HOT',
    tags: ['EN-US', 'HOT'],
    status: 'ACTIVE',
  },
  {
    id: 'hash_drop_us',
    title: 'Dropshipping USA Gadgets',
    hashtags: ['#tiktokmademebuypit', '#amazonfinds', '#musthaves', '#coolgadgets', '#techtrends', '#homefinds', '#viralproduct'],
    languageCode: 'EN-US',
    countryCode: 'US',
    category: 'DROP',
    tags: ['EN-US', 'DROP'],
    status: 'ACTIVE',
  },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp_01',
    name: 'HOT Agosto VIP Drive',
    category: 'HOT',
    accountIds: ['acc_hot_01', 'acc_hot_02', 'acc_hot_03'],
    mediaIds: ['med_01', 'med_02'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    scheduleTimes: ['09:00', '15:00', '21:00'],
    languageCode: 'PT-BR',
    countryCode: 'BR',
    objective: 'Maximize VIP channel subscriptions across target countries',
    status: 'ACTIVE',
  },
  {
    id: 'camp_02',
    name: 'DROP Q3 Fitness & Kitchen Scale',
    category: 'DROP',
    accountIds: ['acc_drop_01', 'acc_drop_03', 'acc_drop_09'],
    mediaIds: ['med_03', 'med_04'],
    startDate: '2026-08-01',
    endDate: '2026-09-15',
    scheduleTimes: ['10:00', '16:00', '20:30'],
    languageCode: 'EN-US',
    countryCode: 'US',
    objective: 'Scale viral physical product sales with localized video variations',
    status: 'ACTIVE',
  },
];

export const INITIAL_QUEUE_JOBS: QueueJob[] = [
  {
    id: 'job_01',
    accountId: 'acc_hot_01',
    accountName: 'Bella VIP Model BR',
    category: 'HOT',
    platform: 'instagram',
    mediaId: 'med_01',
    mediaTitle: 'Hot Summer Glam Promo Video',
    mediaType: 'VIDEO',
    copyId: 'copy_hot_01',
    hashtagId: 'hash_hot_br',
    ctaId: 'cta_pt_br',
    scheduledFor: '2026-08-03 15:00',
    accountLocalTime: '15:00 (São Paulo)',
    status: 'QUEUED',
    attempts: 0,
    createdAt: '2026-08-03 12:00',
  },
  {
    id: 'job_02',
    accountId: 'acc_drop_03',
    accountName: 'FlexFit Gear USA',
    category: 'DROP',
    platform: 'tiktok',
    mediaId: 'med_03',
    mediaTitle: 'Smart Mini Projector Product Reel',
    mediaType: 'VIDEO',
    copyId: 'copy_drop_02',
    hashtagId: 'hash_drop_us',
    ctaId: 'cta_en_us',
    scheduledFor: '2026-08-03 16:00',
    accountLocalTime: '16:00 (Los Angeles)',
    status: 'QUEUED',
    attempts: 0,
    createdAt: '2026-08-03 12:05',
  },
];

export const INITIAL_EXECUTION_LOGS: ExecutionLog[] = [
  {
    id: 'log_01',
    jobId: 'job_hist_88',
    accountId: 'acc_hot_03',
    accountName: 'Scarlett Glam US',
    category: 'HOT',
    platform: 'instagram',
    languageCode: 'EN-US',
    countryCode: 'US',
    mediaTitle: 'Hot Summer Glam Promo Video (Sharp Variant #2)',
    copyUsed: '🔥 Uncensored preview dropped today! Tap the link in bio right now...',
    hashtagsUsed: ['#usmodels', '#vipglam', '#trendingreels'],
    ctaUsed: '👉 Tap the Link in Bio & Order Yours Today!',
    executionTimeMs: 820,
    result: 'SUCCESS',
    statusCode: 200,
    logDetail: '[PublishEngine] Auth valid via Proxy 104.28.19.120:3128. Video dispatched. Post ID: ig_k9x2m1a0',
    timestamp: '2026-08-03 09:00:14',
  },
  {
    id: 'log_02',
    jobId: 'job_hist_89',
    accountId: 'acc_drop_01',
    accountName: 'TechGizmo Brasil',
    category: 'DROP',
    platform: 'tiktok',
    languageCode: 'PT-BR',
    countryCode: 'BR',
    mediaTitle: 'Smart Mini Projector Reel (FFmpeg Speed 1.02x)',
    copyUsed: '😱 Chega de perrengue na cozinha! Esse produto novo...',
    hashtagsUsed: ['#tiktokmademebuypit', '#amazonfinds'],
    ctaUsed: '👉 Clique no Link da Bio e Garanta o Seu Agora!',
    executionTimeMs: 640,
    result: 'SUCCESS',
    statusCode: 200,
    logDetail: '[PublishEngine] TikTok Open API session valid. Video rendered & published. Post ID: tt_7f9a2b1c',
    timestamp: '2026-08-03 11:00:08',
  },
];
